"""Render the full operator matrix and commit it.

For each binary operator, the cross-product of every type on both sides. A pair
nobody considered appears as an explicit `-` cell rather than hiding, and any
later change to the signature tables shows up as a reviewable diff.

    python3 tools/build_matrix.py
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parents[1] / "packages/designer-model/src")
)

from designer_model.expressions import signatures as sig
from designer_model.expressions.types import ALL_TYPES

OUT = (
    pathlib.Path(__file__).resolve().parents[1]
    / "packages/designer-model/tests/operator_matrix.txt"
)

ARITHMETIC_OPS = ("+", "-", "*", "/", "%")
COMPARISON_OPS = ("<", "<=", ">", ">=")
EQUALITY_OPS = ("==", "!=")

NAMES = [t.name for t in ALL_TYPES]
WIDTH = max(len(n) for n in NAMES) + 2


def cell(outcome) -> str:
    if outcome is None:
        return "-"
    if isinstance(outcome, sig.Reject):
        return outcome.code
    return str(outcome)


def table(title: str, resolve) -> list[str]:
    lines = [title, "=" * len(title), ""]
    header = "".ljust(WIDTH) + "".join(n.ljust(WIDTH) for n in NAMES)
    lines += [header, "-" * len(header)]
    for left in NAMES:
        row = left.ljust(WIDTH)
        row += "".join(cell(resolve(left, right)).ljust(WIDTH) for right in NAMES)
        lines.append(row.rstrip())
    lines.append("")
    return lines


def build() -> str:
    lines = [
        "Designer — operator matrix",
        "",
        "Generated by tools/build_matrix.py. Committed so any change to the",
        "signature tables appears as a diff, and so a pair nobody considered",
        "shows up as an explicit '-' rather than hiding.",
        "",
        "  a type name  the result type",
        "  EXPnnn       a deliberate rejection, with the code that explains it",
        "  -            no rule: the combination has no meaning",
        "",
        f"types: {', '.join(NAMES)}",
        "",
    ]
    for op in ARITHMETIC_OPS:
        lines += table(f"a {op} b", lambda x, y, op=op: sig.arithmetic(op, x, y))
    lines += table("a < b   (and <=, >, >=)", sig.comparable)
    lines += table("a == b  (and !=)", sig.equatable)
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(build())
    text = build()
    cells = text.count("EXP")
    print(f"{OUT}  ({len(NAMES)}x{len(NAMES)} per operator, {cells} rejection cells)")
